# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adi Ardana | Web Developer, PHP developer, Full Stack Developer, Wordpress Developer, Front End Developer
email: adhixz@gmail.com
description: >
  Wordpress Developer, Full Stack Developer, Bali Developer, PHP Developer, Front End Developer, Experienced Developer
home-intro: Adi Ardana
profile-image: /image/me.png
home-description: >
  Hi, my name is adi, i am a full stack web developer from Bali-Indonesia.
  I am a passionate developer and learner not by chance but by hobby.
  I am currently working for Ogilvy Digital Bali a.k.a Bullseye as Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adiardana.github.io" # the base hostname & protocol for your site
twitter_username: adhiardana
github_username:  adiardana
github: https://github.com/adiardana
linkedin: https://www.linkedin.com/in/adiardana
twitter: https://twitter.com/adhiardana
pph: http://pph.me/adiardana
permalink: /:categories/:title
gems: [jekyll-paginate]
paginate: 12

# Build settings
markdown: kramdown
