# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adi Ardana
email: adhixz@gmail.com
description: >
  Hi, my name is adi, i am a full stack web developer from Bali-Indonesia.
  I am a passionate developer and learner not by chance but by hobby.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: adhiardana
github_username:  adiardana
github: https://github.com/adiardana
linkedin: https://www.linkedin.com/in/adiardana
permalink: /:categories/:title
gems: [jekyll-paginate]
paginate: 12

# Build settings
markdown: kramdown
